// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/LingoJack/model_infrax/config"
	"github.com/LingoJack/model_infrax/generator"
	"github.com/LingoJack/model_infrax/parser"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序，Wire会自动生成依赖注入代码
// 注意：解析器（DatabaseParser/StatementParser）不再在此处注入
// 而是在 App.Run() 方法中根据配置的 GenerateMode 动态创建
// 这样可以避免 statement 模式下不必要的数据库连接
func InitializeApp(configPath string) (*App, error) {
	configger, err := config.NewConfigger(configPath)
	if err != nil {
		return nil, err
	}
	generatorGenerator := generator.NewGenerator(configger)
	app := NewApp(configger, generatorGenerator)
	return app, nil
}

// InitializeDatabaseParser 单独初始化Parser，用于需要独立使用Parser的场景
func InitializeDatabaseParser(configPath string) (*parser.DatabaseParser, error) {
	configger, err := config.NewConfigger(configPath)
	if err != nil {
		return nil, err
	}
	databaseParser, err := parser.NewDatabaseParser(configger)
	if err != nil {
		return nil, err
	}
	return databaseParser, nil
}

func InitializeStatementParser(configPath string) (*parser.StatementParser, error) {
	configger, err := config.NewConfigger(configPath)
	if err != nil {
		return nil, err
	}
	statementParser, err := parser.NewStatementParser(configger)
	if err != nil {
		return nil, err
	}
	return statementParser, nil
}

func InitializeGenerator(configPath string) (*generator.Generator, error) {
	configger, err := config.NewConfigger(configPath)
	if err != nil {
		return nil, err
	}
	generatorGenerator := generator.NewGenerator(configger)
	return generatorGenerator, nil
}
