// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"model_infrax/config"
	"model_infrax/generator"
	"model_infrax/parser"
	"model_infrax/tool"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序，Wire会自动生成依赖注入代码
func InitializeApp(configPath string) (*App, error) {
	configger, err := config.NewConfigger(configPath)
	if err != nil {
		return nil, err
	}
	parserParser, err := parser.NewParser(configger)
	if err != nil {
		return nil, err
	}
	generator := ProvideGenerator(configger)
	app := NewApp(configger, parserParser, generator)
	return app, nil
}

// InitializeParser 单独初始化Parser，用于需要独立使用Parser的场景
func InitializeParser(configPath string) (*parser.Parser, error) {
	configger, err := config.NewConfigger(configPath)
	if err != nil {
		return nil, err
	}
	parserParser, err := parser.NewParser(configger)
	if err != nil {
		return nil, err
	}
	return parserParser, nil
}

// wire.go:

// ProvideGenerator 提供 Generator 实例
func ProvideGenerator(cfg *config.Configger) *generator.Generator {
	templatePath := "./assert/template/model.template"

	outputPath := tool.EscapeHomeDir(cfg.GenerateOption.OutputPath)
	return generator.NewGenerator(templatePath, outputPath)
}
